apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: spin-operator
  namespace: spin-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: spin-operator
      version: "0.0.2"
      sourceRef:
        kind: HelmRepository
        name: spin-operator
        namespace: spin-operator
      interval: 12h
  values:
    installCRDs: true
