apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kwasm-node-installer
  namespace: kwasm-system
  labels:
    app: kwasm-node-installer
spec:
  selector:
    matchLabels:
      app: kwasm-node-installer
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kwasm-node-installer
    spec:
      hostPID: true
      volumes:
        - name: node-root
          hostPath:
            path: /
      initContainers:
        - name: kwasm-provision
          image: ghcr.io/spinkube/containerd-shim-spin/node-installer:v0.13.0
          securityContext:
            privileged: true
          env:
            - name: NODE_ROOT
              value: /mnt/node-root
          volumeMounts:
            - name: node-root
              mountPath: /mnt/node-root
      containers:
        - image: k8s.gcr.io/pause:3.9
          name: pause
